

server {
    listen 80;
    listen [::]:80;

    location / {
        auth_request "/auth";
        proxy_pass "http://ollama-tabby:11434/";
    }

    location /auth {
        proxy_pass "http://ollama-auth-provider:8080/auth";
    }
}

